### ISSUE TITLE
Any plans on working on this project again ?

### ISSUE THREAD

**Issue by chrissunny94** [againerju/tcg_recognition#1]
Hello ,

I have been trying to run your code after being really impressed with the paper . 

But bumping into a lot of problems when runing it . 
```

ypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

would be grateful , if you guys can update this repo .

If a docker image or a virtual env can be created , much appreciated .

Anyhow , amazing work guys .

**Comment by chrissunny94** [comment]
https://github.com/chrissunny94/tcg_recognition


Created a fork 

Issues being tracked 

1.  requirements.txt , missing '=' symbol .

**Comment by chrissunny94** [comment]
2nd issue 

Running the followning command 

`pip install -r requirements.txt`


Get the following error 
```
Defaulting to user installation because normal site-packages is not writeable
Collecting h5py==2.10.0 (from -r requirements.txt (line 1))
  Downloading h5py-2.10.0-cp38-cp38-manylinux1_x86_64.whl (2.9 MB)
2.9/2.9 MB 4.4 MB/s eta 0:00:00
ERROR: Could not find a version that satisfies the requirement tensorflow==2.0.0 (from versions: 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.7.0rc0, 2.7.0rc1, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.7.4, 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.11.1, 2.12.0rc0, 2.12.0rc1, 2.12.0, 2.13.0rc0)
ERROR: No matching distribution found for tensorflow==2.0.0
```

**Comment by chrissunny94** [comment]
changed tesnsorflow version from 2.0.0. to 2.2.0

```

(venv_name) chris@enoch:~/tcg_recognition$ pip install -r requirements.txt
Collecting h5py==2.10.0
  Using cached h5py-2.10.0-cp38-cp38-manylinux1_x86_64.whl (2.9 MB)
Collecting tensorflow==2.2.0
  Downloading tensorflow-2.2.0-cp38-cp38-manylinux2010_x86_64.whl (516.3 MB)
     |████████████████████████████████| 516.3 MB 6.7 kB/s 
Collecting Keras==2.3.1
  Downloading Keras-2.3.1-py2.py3-none-any.whl (377 kB)
     |████████████████████████████████| 377 kB 5.3 MB/s 
Collecting matplotlib==3.3.1
  Downloading matplotlib-3.3.1-cp38-cp38-manylinux1_x86_64.whl (11.6 MB)
     |████████████████████████████████| 11.6 MB 4.2 MB/s 
Collecting numpy==1.17.2
  Downloading numpy-1.17.2.zip (6.5 MB)
     |████████████████████████████████| 6.5 MB 4.2 MB/s 
Collecting tqdm==4.48.2
  Downloading tqdm-4.48.2-py2.py3-none-any.whl (68 kB)
     |████████████████████████████████| 68 kB 3.9 MB/s 
Collecting keras_self_attention==0.42.0
  Downloading keras-self-attention-0.42.0.tar.gz (9.3 kB)
Collecting scikit_learn==0.23.2
  Downloading scikit_learn-0.23.2-cp38-cp38-manylinux1_x86_64.whl (6.8 MB)
     |████████████████████████████████| 6.8 MB 4.3 MB/s 
Collecting six
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting grpcio>=1.8.6
  Downloading grpcio-1.54.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.1 MB)
     |████████████████████████████████| 5.1 MB 4.1 MB/s 
Collecting opt-einsum>=2.3.2
  Downloading opt_einsum-3.3.0-py3-none-any.whl (65 kB)
     |████████████████████████████████| 65 kB 2.3 MB/s 
Collecting keras-preprocessing>=1.1.0
  Downloading Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 1.0 MB/s 
Collecting wrapt>=1.11.1
  Downloading wrapt-1.15.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (81 kB)
     |████████████████████████████████| 81 kB 12.5 MB/s 
Collecting protobuf>=3.8.0
  Downloading protobuf-4.23.1-cp37-abi3-manylinux2014_x86_64.whl (304 kB)
     |████████████████████████████████| 304 kB 4.3 MB/s 
Collecting tensorflow-estimator<2.3.0,>=2.2.0
  Downloading tensorflow_estimator-2.2.0-py2.py3-none-any.whl (454 kB)
     |████████████████████████████████| 454 kB 4.5 MB/s 
Collecting google-pasta>=0.1.8
  Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
     |████████████████████████████████| 57 kB 2.9 MB/s 
Collecting astunparse==1.6.3
  Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Collecting tensorboard<2.3.0,>=2.2.0
  Downloading tensorboard-2.2.2-py3-none-any.whl (3.0 MB)
     |████████████████████████████████| 3.0 MB 4.7 MB/s 
Collecting scipy==1.4.1; python_version >= "3"
  Downloading scipy-1.4.1-cp38-cp38-manylinux1_x86_64.whl (26.0 MB)
     |████████████████████████████████| 26.0 MB 3.6 MB/s 
Collecting absl-py>=0.7.0
  Downloading absl_py-1.4.0-py3-none-any.whl (126 kB)
     |████████████████████████████████| 126 kB 5.6 MB/s 
Collecting wheel>=0.26; python_version >= "3"
  Downloading wheel-0.40.0-py3-none-any.whl (64 kB)
     |████████████████████████████████| 64 kB 2.3 MB/s 
Collecting gast==0.3.3
  Downloading gast-0.3.3-py2.py3-none-any.whl (9.7 kB)
Collecting termcolor>=1.1.0
  Downloading termcolor-2.3.0-py3-none-any.whl (6.9 kB)
Collecting keras-applications>=1.0.6
  Downloading Keras_Applications-1.0.8-py3-none-any.whl (50 kB)
     |████████████████████████████████| 50 kB 4.2 MB/s 
Collecting pyyaml
  Downloading PyYAML-6.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (701 kB)
     |████████████████████████████████| 701 kB 5.4 MB/s 
Collecting cycler>=0.10
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting python-dateutil>=2.1
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting pillow>=6.2.0
  Downloading Pillow-9.5.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 4.9 MB/s 
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.4.4-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.2 MB)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting certifi>=2020.06.20
  Downloading certifi-2023.5.7-py3-none-any.whl (156 kB)
     |████████████████████████████████| 156 kB 5.6 MB/s 
Collecting threadpoolctl>=2.0.0
  Downloading threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Collecting joblib>=0.11
  Downloading joblib-1.2.0-py3-none-any.whl (297 kB)
     |████████████████████████████████| 297 kB 6.2 MB/s 
Collecting google-auth-oauthlib<0.5,>=0.4.1
  Downloading google_auth_oauthlib-0.4.6-py2.py3-none-any.whl (18 kB)
Requirement already satisfied: setuptools>=41.0.0 in ./venv_name/lib/python3.8/site-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow==2.2.0->-r requirements.txt (line 3)) (44.0.0)
Collecting requests<3,>=2.21.0
  Downloading requests-2.30.0-py3-none-any.whl (62 kB)
     |████████████████████████████████| 62 kB 949 kB/s 
Collecting tensorboard-plugin-wit>=1.6.0
  Downloading tensorboard_plugin_wit-1.8.1-py3-none-any.whl (781 kB)
     |████████████████████████████████| 781 kB 6.0 MB/s 
Collecting google-auth<2,>=1.6.3
  Downloading google_auth-1.35.0-py2.py3-none-any.whl (152 kB)
     |████████████████████████████████| 152 kB 5.3 MB/s 
Collecting markdown>=2.6.8
  Using cached Markdown-3.4.3-py3-none-any.whl (93 kB)
Collecting werkzeug>=0.11.15
  Downloading Werkzeug-2.3.4-py3-none-any.whl (242 kB)
     |████████████████████████████████| 242 kB 6.1 MB/s 
Collecting requests-oauthlib>=0.7.0
  Downloading requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Collecting urllib3<3,>=1.21.1
  Downloading urllib3-2.0.2-py3-none-any.whl (123 kB)
     |████████████████████████████████| 123 kB 5.0 MB/s 
Collecting idna<4,>=2.5
  Downloading idna-3.4-py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 94 kB/s 
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.1.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (195 kB)
Collecting cachetools<5.0,>=2.0.0
  Downloading cachetools-4.2.4-py3-none-any.whl (10 kB)
Collecting pyasn1-modules>=0.2.1
  Downloading pyasn1_modules-0.3.0-py2.py3-none-any.whl (181 kB)
     |████████████████████████████████| 181 kB 5.6 MB/s 
Collecting rsa<5,>=3.1.4; python_version >= "3.6"
  Downloading rsa-4.9-py3-none-any.whl (34 kB)
Collecting importlib-metadata>=4.4; python_version < "3.10"
  Downloading importlib_metadata-6.6.0-py3-none-any.whl (22 kB)
Collecting MarkupSafe>=2.1.1
  Downloading MarkupSafe-2.1.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Collecting oauthlib>=3.0.0
  Downloading oauthlib-3.2.2-py3-none-any.whl (151 kB)
     |████████████████████████████████| 151 kB 6.5 MB/s 
Collecting pyasn1<0.6.0,>=0.4.6
  Downloading pyasn1-0.5.0-py2.py3-none-any.whl (83 kB)
     |████████████████████████████████| 83 kB 1.9 MB/s 
Collecting zipp>=0.5
  Using cached zipp-3.15.0-py3-none-any.whl (6.8 kB)
Building wheels for collected packages: numpy, keras-self-attention
  Building wheel for numpy (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/chris/tcg_recognition/venv_name/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jimequof/numpy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jimequof/numpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-tvk752k_
       cwd: /tmp/pip-install-jimequof/numpy/
  Complete output (7 lines):
  Running from numpy source directory.
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for numpy
  Running setup.py clean for numpy
  ERROR: Command errored out with exit status 1:
   command: /home/chris/tcg_recognition/venv_name/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jimequof/numpy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jimequof/numpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: /tmp/pip-install-jimequof/numpy
  Complete output (10 lines):
  Running from numpy source directory.
  
  `setup.py clean` is not supported, use one of the following instead:
  
    - `git clean -xdf` (cleans all files)
    - `git clean -Xdf` (cleans all versioned files, doesn't touch
                        files that aren't checked into the git repo)
  
  Add `--force` to your command to use it anyway if you must (unsupported).
  
  ----------------------------------------
  ERROR: Failed cleaning build dir for numpy
  Building wheel for keras-self-attention (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/chris/tcg_recognition/venv_name/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jimequof/keras-self-attention/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jimequof/keras-self-attention/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-2xlr31fn
       cwd: /tmp/pip-install-jimequof/keras-self-attention/
  Complete output (7 lines):
  Warning: 'classifiers' should be a list, got type 'tuple'
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for keras-self-attention
  Running setup.py clean for keras-self-attention
Failed to build numpy keras-self-attention
Installing collected packages: six, numpy, h5py, grpcio, opt-einsum, keras-preprocessing, wrapt, protobuf, tensorflow-estimator, google-pasta, wheel, astunparse, absl-py, urllib3, certifi, idna, charset-normalizer, requests, oauthlib, requests-oauthlib, cachetools, pyasn1, pyasn1-modules, rsa, google-auth, google-auth-oauthlib, tensorboard-plugin-wit, zipp, importlib-metadata, markdown, MarkupSafe, werkzeug, tensorboard, scipy, gast, termcolor, tensorflow, keras-applications, pyyaml, Keras, cycler, python-dateutil, pillow, kiwisolver, pyparsing, matplotlib, tqdm, keras-self-attention, threadpoolctl, joblib, scikit-learn
    Running setup.py install for numpy ... done
    Running setup.py install for keras-self-attention ... done
Successfully installed Keras-2.3.1 MarkupSafe-2.1.2 absl-py-1.4.0 astunparse-1.6.3 cachetools-4.2.4 certifi-2023.5.7 charset-normalizer-3.1.0 cycler-0.11.0 gast-0.3.3 google-auth-1.35.0 google-auth-oauthlib-0.4.6 google-pasta-0.2.0 grpcio-1.54.2 h5py-2.10.0 idna-3.4 importlib-metadata-6.6.0 joblib-1.2.0 keras-applications-1.0.8 keras-preprocessing-1.1.2 keras-self-attention-0.42.0 kiwisolver-1.4.4 markdown-3.4.3 matplotlib-3.3.1 numpy-1.17.2 oauthlib-3.2.2 opt-einsum-3.3.0 pillow-9.5.0 protobuf-4.23.1 pyasn1-0.5.0 pyasn1-modules-0.3.0 pyparsing-3.0.9 python-dateutil-2.8.2 pyyaml-6.0 requests-2.30.0 requests-oauthlib-1.3.1 rsa-4.9 scikit-learn-0.23.2 scipy-1.4.1 six-1.16.0 tensorboard-2.2.2 tensorboard-plugin-wit-1.8.1 tensorflow-2.2.0 tensorflow-estimator-2.2.0 termcolor-2.3.0 threadpoolctl-3.1.0 tqdm-4.48.2 urllib3-2.0.2 werkzeug-2.3.4 wheel-0.40.0 wrapt-1.15.0 zipp-3.15.0
```

**Comment by chrissunny94** [comment]
Update 3
from 0.42.0
updated the keras_self_attention==0.43.0

```

(venv_name) chris@enoch:~/tcg_recognition$ pip install -r requirements.txt 
Requirement already satisfied: h5py==2.10.0 in ./venv_name/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (2.10.0)
Requirement already satisfied: tensorflow==2.2.0 in ./venv_name/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (2.2.0)
Requirement already satisfied: Keras==2.3.1 in ./venv_name/lib/python3.8/site-packages (from -r requirements.txt (line 4)) (2.3.1)
Requirement already satisfied: matplotlib==3.3.1 in ./venv_name/lib/python3.8/site-packages (from -r requirements.txt (line 5)) (3.3.1)
Requirement already satisfied: numpy==1.17.2 in ./venv_name/lib/python3.8/site-packages (from -r requirements.txt (line 6)) (1.17.2)
Requirement already satisfied: tqdm==4.48.2 in ./venv_name/lib/python3.8/site-packages (from -r requirements.txt (line 7)) (4.48.2)
Collecting keras_self_attention==0.43.0
  Downloading keras-self-attention-0.43.0.tar.gz (11 kB)
Requirement already satisfied: scikit_learn==0.23.2 in ./venv_name/lib/python3.8/site-packages (from -r requirements.txt (line 9)) (0.23.2)
Requirement already satisfied: six in ./venv_name/lib/python3.8/site-packages (from h5py==2.10.0->-r requirements.txt (line 1)) (1.16.0)
Requirement already satisfied: tensorflow-estimator<2.3.0,>=2.2.0 in ./venv_name/lib/python3.8/site-packages (from tensorflow==2.2.0->-r requirements.txt (line 3)) (2.2.0)
Requirement already satisfied: termcolor>=1.1.0 in ./venv_name/lib/python3.8/site-packages (from tensorflow==2.2.0->-r requirements.txt (line 3)) (2.3.0)
Requirement already satisfied: astunparse==1.6.3 in ./venv_name/lib/python3.8/site-packages (from tensorflow==2.2.0->-r requirements.txt (line 3)) (1.6.3)
Requirement already satisfied: grpcio>=1.8.6 in ./venv_name/lib/python3.8/site-packages (from tensorflow==2.2.0->-r requirements.txt (line 3)) (1.54.2)
Requirement already satisfied: protobuf>=3.8.0 in ./venv_name/lib/python3.8/site-packages (from tensorflow==2.2.0->-r requirements.txt (line 3)) (4.23.1)
Requirement already satisfied: scipy==1.4.1; python_version >= "3" in ./venv_name/lib/python3.8/site-packages (from tensorflow==2.2.0->-r requirements.txt (line 3)) (1.4.1)
Requirement already satisfied: tensorboard<2.3.0,>=2.2.0 in ./venv_name/lib/python3.8/site-packages (from tensorflow==2.2.0->-r requirements.txt (line 3)) (2.2.2)
Requirement already satisfied: opt-einsum>=2.3.2 in ./venv_name/lib/python3.8/site-packages (from tensorflow==2.2.0->-r requirements.txt (line 3)) (3.3.0)
Requirement already satisfied: gast==0.3.3 in ./venv_name/lib/python3.8/site-packages (from tensorflow==2.2.0->-r requirements.txt (line 3)) (0.3.3)
Requirement already satisfied: absl-py>=0.7.0 in ./venv_name/lib/python3.8/site-packages (from tensorflow==2.2.0->-r requirements.txt (line 3)) (1.4.0)
Requirement already satisfied: google-pasta>=0.1.8 in ./venv_name/lib/python3.8/site-packages (from tensorflow==2.2.0->-r requirements.txt (line 3)) (0.2.0)
Requirement already satisfied: wrapt>=1.11.1 in ./venv_name/lib/python3.8/site-packages (from tensorflow==2.2.0->-r requirements.txt (line 3)) (1.15.0)
Requirement already satisfied: wheel>=0.26; python_version >= "3" in ./venv_name/lib/python3.8/site-packages (from tensorflow==2.2.0->-r requirements.txt (line 3)) (0.40.0)
Requirement already satisfied: keras-preprocessing>=1.1.0 in ./venv_name/lib/python3.8/site-packages (from tensorflow==2.2.0->-r requirements.txt (line 3)) (1.1.2)
Requirement already satisfied: keras-applications>=1.0.6 in ./venv_name/lib/python3.8/site-packages (from Keras==2.3.1->-r requirements.txt (line 4)) (1.0.8)
Requirement already satisfied: pyyaml in ./venv_name/lib/python3.8/site-packages (from Keras==2.3.1->-r requirements.txt (line 4)) (6.0)
Requirement already satisfied: pillow>=6.2.0 in ./venv_name/lib/python3.8/site-packages (from matplotlib==3.3.1->-r requirements.txt (line 5)) (9.5.0)
Requirement already satisfied: certifi>=2020.06.20 in ./venv_name/lib/python3.8/site-packages (from matplotlib==3.3.1->-r requirements.txt (line 5)) (2023.5.7)
Requirement already satisfied: kiwisolver>=1.0.1 in ./venv_name/lib/python3.8/site-packages (from matplotlib==3.3.1->-r requirements.txt (line 5)) (1.4.4)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in ./venv_name/lib/python3.8/site-packages (from matplotlib==3.3.1->-r requirements.txt (line 5)) (3.0.9)
Requirement already satisfied: cycler>=0.10 in ./venv_name/lib/python3.8/site-packages (from matplotlib==3.3.1->-r requirements.txt (line 5)) (0.11.0)
Requirement already satisfied: python-dateutil>=2.1 in ./venv_name/lib/python3.8/site-packages (from matplotlib==3.3.1->-r requirements.txt (line 5)) (2.8.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./venv_name/lib/python3.8/site-packages (from scikit_learn==0.23.2->-r requirements.txt (line 9)) (3.1.0)
Requirement already satisfied: joblib>=0.11 in ./venv_name/lib/python3.8/site-packages (from scikit_learn==0.23.2->-r requirements.txt (line 9)) (1.2.0)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in ./venv_name/lib/python3.8/site-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow==2.2.0->-r requirements.txt (line 3)) (0.4.6)
Requirement already satisfied: markdown>=2.6.8 in ./venv_name/lib/python3.8/site-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow==2.2.0->-r requirements.txt (line 3)) (3.4.3)
Requirement already satisfied: requests<3,>=2.21.0 in ./venv_name/lib/python3.8/site-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow==2.2.0->-r requirements.txt (line 3)) (2.30.0)
Requirement already satisfied: werkzeug>=0.11.15 in ./venv_name/lib/python3.8/site-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow==2.2.0->-r requirements.txt (line 3)) (2.3.4)
Requirement already satisfied: setuptools>=41.0.0 in ./venv_name/lib/python3.8/site-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow==2.2.0->-r requirements.txt (line 3)) (44.0.0)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in ./venv_name/lib/python3.8/site-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow==2.2.0->-r requirements.txt (line 3)) (1.8.1)
Requirement already satisfied: google-auth<2,>=1.6.3 in ./venv_name/lib/python3.8/site-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow==2.2.0->-r requirements.txt (line 3)) (1.35.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in ./venv_name/lib/python3.8/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.3.0,>=2.2.0->tensorflow==2.2.0->-r requirements.txt (line 3)) (1.3.1)
Requirement already satisfied: importlib-metadata>=4.4; python_version < "3.10" in ./venv_name/lib/python3.8/site-packages (from markdown>=2.6.8->tensorboard<2.3.0,>=2.2.0->tensorflow==2.2.0->-r requirements.txt (line 3)) (6.6.0)
Requirement already satisfied: charset-normalizer<4,>=2 in ./venv_name/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard<2.3.0,>=2.2.0->tensorflow==2.2.0->-r requirements.txt (line 3)) (3.1.0)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./venv_name/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard<2.3.0,>=2.2.0->tensorflow==2.2.0->-r requirements.txt (line 3)) (2.0.2)
Requirement already satisfied: idna<4,>=2.5 in ./venv_name/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard<2.3.0,>=2.2.0->tensorflow==2.2.0->-r requirements.txt (line 3)) (3.4)
Requirement already satisfied: MarkupSafe>=2.1.1 in ./venv_name/lib/python3.8/site-packages (from werkzeug>=0.11.15->tensorboard<2.3.0,>=2.2.0->tensorflow==2.2.0->-r requirements.txt (line 3)) (2.1.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in ./venv_name/lib/python3.8/site-packages (from google-auth<2,>=1.6.3->tensorboard<2.3.0,>=2.2.0->tensorflow==2.2.0->-r requirements.txt (line 3)) (0.3.0)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in ./venv_name/lib/python3.8/site-packages (from google-auth<2,>=1.6.3->tensorboard<2.3.0,>=2.2.0->tensorflow==2.2.0->-r requirements.txt (line 3)) (4.2.4)
Requirement already satisfied: rsa<5,>=3.1.4; python_version >= "3.6" in ./venv_name/lib/python3.8/site-packages (from google-auth<2,>=1.6.3->tensorboard<2.3.0,>=2.2.0->tensorflow==2.2.0->-r requirements.txt (line 3)) (4.9)
Requirement already satisfied: oauthlib>=3.0.0 in ./venv_name/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.3.0,>=2.2.0->tensorflow==2.2.0->-r requirements.txt (line 3)) (3.2.2)
Requirement already satisfied: zipp>=0.5 in ./venv_name/lib/python3.8/site-packages (from importlib-metadata>=4.4; python_version < "3.10"->markdown>=2.6.8->tensorboard<2.3.0,>=2.2.0->tensorflow==2.2.0->-r requirements.txt (line 3)) (3.15.0)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in ./venv_name/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard<2.3.0,>=2.2.0->tensorflow==2.2.0->-r requirements.txt (line 3)) (0.5.0)
Building wheels for collected packages: keras-self-attention
  Building wheel for keras-self-attention (setup.py) ... done
  Created wheel for keras-self-attention: filename=keras_self_attention-0.43.0-py3-none-any.whl size=17399 sha256=594df45a9418c0125e0e44ee614b3e7a21840e9d60e03ef63c04db698d5c615c
  Stored in directory: /home/chris/.cache/pip/wheels/79/52/a0/8f044afbae4cba7e7899baefa9fd3447392a76a10dbdb721c7
Successfully built keras-self-attention
Installing collected packages: keras-self-attention
  Attempting uninstall: keras-self-attention
    Found existing installation: keras-self-attention 0.42.0
    Uninstalling keras-self-attention-0.42.0:
      Successfully uninstalled keras-self-attention-0.42.0
Successfully installed keras-self-attention-0.43.0
```




```
`(venv_name) chris@enoch:~/tcg_recognition$ python3 evaluate.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "evaluate.py", line 9, in <module>
    import utils
  File "/home/chris/tcg_recognition/utils.py", line 9, in <module>
    import keras
  File "/home/chris/tcg_recognition/venv_name/lib/python3.8/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/home/chris/tcg_recognition/venv_name/lib/python3.8/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/home/chris/tcg_recognition/venv_name/lib/python3.8/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/home/chris/tcg_recognition/venv_name/lib/python3.8/site-packages/keras/backend/__init__.py", line 1, in <module>
    from .load_backend import epsilon
  File "/home/chris/tcg_recognition/venv_name/lib/python3.8/site-packages/keras/backend/load_backend.py", line 90, in <module>
    from .tensorflow_backend import *
  File "/home/chris/tcg_recognition/venv_name/lib/python3.8/site-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "/home/chris/tcg_recognition/venv_name/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/chris/tcg_recognition/venv_name/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 53, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/home/chris/tcg_recognition/venv_name/lib/python3.8/site-packages/tensorflow/core/framework/graph_pb2.py", line 16, in <module>
    from tensorflow.core.framework import function_pb2 as tensorflow_dot_core_dot_framework_dot_function__pb2
  File "/home/chris/tcg_recognition/venv_name/lib/python3.8/site-packages/tensorflow/core/framework/function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/home/chris/tcg_recognition/venv_name/lib/python3.8/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/home/chris/tcg_recognition/venv_name/lib/python3.8/site-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/home/chris/tcg_recognition/venv_name/lib/python3.8/site-packages/tensorflow/core/framework/resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "/home/chris/tcg_recognition/venv_name/lib/python3.8/site-packages/tensorflow/core/framework/tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/home/chris/tcg_recognition/venv_name/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates`
```

**Comment by chrissunny94** [comment]
I think i have to modify the **config/config.ini**

These settings ,

```
[path]
tcg_root = /home/chris/tcg_recognition/config/..
baseline_root = /home/chris/tcg_recognition/config/../baselines
run_root = /home/chris/tcg_recognition/config/../runs

```

but some confusion on this .
